name: Build management
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: list env
        run: env

      - name: docker build management
        run: docker build -f management/web/Dockerfile -t docker.pkg.github.com/${GITHUB_REPOSITORY}/management:${GITHUB_REF##*/}-${GITHUB_RUN_NUMBER} -t docker.pkg.github.com/${GITHUB_REPOSITORY}/management:latest management/web

      - name: docker images 
        run: docker images

      - name: docker login
        run : docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY%/*} -p ${{ secrets.packages_token }}

      - name: docker push management tag branch number
        run : docker push docker.pkg.github.com/${GITHUB_REPOSITORY}/management:${GITHUB_REF##*/}-${GITHUB_RUN_NUMBER}
      
      - name: docker push management tag latest
        run: docker push docker.pkg.github.com/${GITHUB_REPOSITORY}/management:latest