name: Build product-service
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: list env
        run: env

      - name: docker build product-service
        run: docker build -f product-service/api/Dockerfile -t docker.pkg.github.com/${GITHUB_REPOSITORY}/product_service_api:${GITHUB_REF##*/}-${GITHUB_RUN_NUMBER} -t docker.pkg.github.com/${GITHUB_REPOSITORY}/product_service_api:latest product-service/api 

      - name: docker images 
        run: docker images

      - name: docker login
        run : docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY%/*} -p ${{ secrets.packages_token }}

      - name: docker push product_service_api tag branch number
        run : docker push docker.pkg.github.com/${GITHUB_REPOSITORY}/product_service_api:${GITHUB_REF##*/}-${GITHUB_RUN_NUMBER}
      
      - name: docker push product_service_api tag latest
        run: docker push docker.pkg.github.com/${GITHUB_REPOSITORY}/product_service_api:latest