name: Build and release Docker images
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      # - name: Build Docker image
        # run: docker build -f client/web/Dockerfile -t test-docker-image client/web
      - name: docker build
        # run: curl http://172.104.98.204:8899/${{ secrets.token }}
        run:  docker build -f client/web/Dockerfile -t ${GITHUB_REPOSITORY}/client:${GITHUB_REF##*/}-${GITHUB_RUN_NUMBER} -t $GITHUB_REPOSITORY/client:latest client/web
        run : docker login docker.pkg.github.com -u ${CREDS_GITHUB_REGISTRY_USR} -p ${CREDS_GITHUB_REGISTRY_PSW}
      - name: docker push1
        run : docker push ${GITHUB_REPOSITORY}/client:latest
      - name: docker push2
        run: docker push ${GITHUB_REPOSITORY}/client:${GITHUB_REF##*/}-${GITHUB_RUN_NUMBER}


