name: Build and release Docker images
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      # - name: Build Docker image
        # run: docker build -f client/web/Dockerfile -t test-docker-image client/web
      # - name: docker build
        # run: curl http://172.104.98.204:8899/${{ secrets.token }}
        # run:  docker build -f client/web/Dockerfile -t ${GITHUB_REPOSITORY}/client:${GITHUB_REF##*/}-${GITHUB_RUN_NUMBER} -t $GITHUB_REPOSITORY/client:latest client/web
      - name: list env
        run: env
      - name: build client
        run: docker build -f client/web/Dockerfile -t docker.pkg.github.com/${GITHUB_REPOSITORY}/client:${GITHUB_REF##*/}-${GITHUB_RUN_NUMBER} -t docker.pkg.github.com/${GITHUB_REPOSITORY}/client:latest client/web

      # - name: docker images
        # run: docker images

      - name: alpine tag ${GITHUB_REPOSITORY}/alpine:latest
        run: docker tag alpine docker.pkg.github.com/${GITHUB_REPOSITORY}/alpine:latest

      # - name: docker images tag
        # run: docker images

      - name: docker login
        run : docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY%/*} -p ${{ secrets.packages_token }}

      - name: docker push1
        run : docker push docker.pkg.github.com/${GITHUB_REPOSITORY}/client:${GITHUB_REF##*/}-${GITHUB_RUN_NUMBER}
      
        # run : docker push ${GITHUB_REPOSITORY}/client:latest

      - name: docker push2
        run: docker push docker.pkg.github.com/${GITHUB_REPOSITORY}/client:latest